import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import { generateHtmlPlugin } from './src/frontend/generate-html-plugin';

// Use process.cwd() for better compatibility with build environments like Vercel
const projectRoot = process.cwd();
const frontendRoot = path.resolve(projectRoot, 'src', 'frontend');
const outputDir = path.resolve(projectRoot, 'dist', 'client');

export default defineConfig({
  plugins: [
    generateHtmlPlugin(), // Generate HTML programmatically
    react()
  ],
  root: frontendRoot,
  build: {
    outDir: outputDir,
    emptyOutDir: true,
    assetsDir: 'assets',
    base: '/',
    // HTML is auto-generated by generateHtmlPlugin
  },
  server: {
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://localhost:3001',
        changeOrigin: true
      },
      '/chat': {
        target: 'http://localhost:3001',
        changeOrigin: true,
        ws: true
      }
    }
  },
  resolve: {
    alias: [
      {
        find: '@',
        replacement: frontendRoot
      },
      {
        find: /^~lib\/(.*)$/,
        replacement: path.resolve(projectRoot, 'src', 'lib', '$1')
      }
    ],
    // Ensure TypeScript files can be resolved without extensions
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.json']
  },
  publicDir: path.resolve(projectRoot, 'public'),
  clearScreen: false
});
